# sudo docker build ./
# sudo docker images
# sudo docker-compose up -d --build

version: '3.9'

services:
  app:
    build: ./
    container_name: 'spring-app'
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
