# sudo docker build ./
# sudo docker images
# sudo docker-compose up -d --build

version: '3'

services:
  app:
    build: ./
    container_name: spring-app
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '0.500'
          memory: 512M